image: node:alpine

stages:
  - build
  - deploy

build:
  stage: build
  script:
    - npm ci
    - npm run lint
    - npm run build
  only:
    - tags
  cache:
    key: node_modules
    paths:
    - node_modules/
  artifacts:
    paths:
      - public/

deploy:
  stage: deploy
  environment:
    name: production
    url: https://jouni.jappinen.fi
  before_script:
    - npm i -g netlify-cli@2.0.0-beta.5
  script:
    - netlify deploy -d public --prod -m $CI_COMMIT_TAG
  only:
    - tags
