stages:
  - build
  - deploy

build:
  stage: build
  image: docker:stable
  services:
    - docker:dind
  variables:
    DOCKER_HOST: tcp://docker:2375/
    DOCKER_DRIVER: overlay2
    IMAGE_LATEST_TAG: $CI_REGISTRY_IMAGE:latest
    IMAGE_COMMIT_TAG: $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG
  before_script:
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
  script:
    - docker pull $IMAGE_LATEST_TAG
    - docker build --cache-from $IMAGE_LATEST_TAG -t $IMAGE_COMMIT_TAG .
    - docker tag $IMAGE_COMMIT_TAG $IMAGE_LATEST_TAG
    - docker push $IMAGE_COMMIT_TAG
    - docker push $IMAGE_LATEST_TAG
  only:
    - tags

build_static:
  image: node:alpine
  stage: build
  script:
    - npm ci
    - npm run lint
    - npm run build
  artifacts:
    paths:
      - public

deploy_static:
  image: node:alpine
  stage: deploy
  environment:
    name: production
    url: https://jouni.jappinen.fi
  before_script:
    - npm i -g netlify-cli@next
  script:
    - netlify deploy -d public --prod
  only:
    - tags
