image: node:alpine

stages:
  - install
  - test
  - build
  - deploy

"Install":
  stage: install
  script:
    - npm ci
  artifacts:
    expire_in: 1 day
    paths:
      - node_modules
  cache:
    paths:
      - node_modules

"Lint":
  stage: test
  script:
    - npm run lint

"Build":
  stage: build
  script:
    - npm run build
  artifacts:
    paths:
      - public

"Netlify":
  stage: deploy
  environment:
    name: production
    url: https://jouni.jappinen.fi
  before_script:
    - apk add --no-cache curl tar
    - curl -sL https://cli.netlify.com/download/latest/linux | tar xz
  script:
    - ./netlifyctl deploy -A $NETLIFY_ACCESS_TOKEN -s $NETLIFY_SITE_ID -P public -m $CI_COMMIT_TAG
  only:
    - tags
