image: node:alpine

stages:
  - build
  - deploy

build:
  stage: build
  script:
    - npm ci
    - npm run lint
    - npm run build
  only:
    - tags
  artifacts:
    paths:
      - public

deploy:
  stage: deploy
  environment:
    name: production
    url: https://jouni.jappinen.fi
  before_script:
    - npm i -g netlify-cli@next
  script:
    - netlify deploy -d public --prod
  only:
    - tags
