name = "jouni-dev"

compatibility_date = "2023-01-15"
compatibility_flags = [
  "streams_enable_constructors",
  "transformstream_enable_standard_constructor"
]

workers_dev = false
route = "https://jouni.jappinen.fi/*"

main = "./build/index.js"

[site]
bucket = "./public"

[build]
command = "npm run build"

[vars]
CF_BEACON_TOKEN = ""

[env.production]
name = "jouni"

[env.production.vars]
CF_BEACON_TOKEN = "4870e83b9f124192a6e7edb40b569e8f"
