name = "jouni_jappinen_fi"
type = "javascript"
workers_dev = false
# account_id = $CF_ACCOUNT_ID
# zone_id = $CF_ZONE_ID
route = "jouni.jappinen.fi/*"

[site]
bucket = "./dist"
entry-point = "workers-site"

[build]
upload.format = "service-worker"
command = "npm run build"
